FROM golang:1.21rc3-alpine3.18

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
EXPOSE 5300
ENV PACKAGE_SERVICE_ADDRESS=package_service:5301
RUN go build -v -o /usr/local/bin/package_service ./services/package_service/cmd

CMD ["/usr/local/bin/package_service"]
