FROM golang:1.21rc3-alpine3.18

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
EXPOSE 5300
ENV USER_SERVICE_ADDRESS=user_service:5300
RUN go build -v -o /usr/local/bin/user_service ./services/user_service/cmd

CMD ["/usr/local/bin/user_service"]
